---
- name: Add or update user password
  hosts: all
  become: true  
  

  tasks:
  - name: Change "george" passwd
    user:
      name: george
      update_password: always
      password: "{{ newpassword|password_hash('sha512')  }}"  
