---
- name: Mount SMB Linux share
  become: true
  vars:
    uri: "//windows-pc/share"
    username: "example@crab"
    password: "password"
    mountpoint: "/share"
  tasks:
    - name: Устанавливаем пакет для работы с cifs
      paсkage:
        name: cifs-utils
        state: present

    - name: check mountpoint exists
      file:
        path: "{{ mountpoint }}"
        state: directory
        mode: '0755'
        owner: 'root'
        group: 'root'

    - name: mount share
      mount:
        src: "{{ uri }}"
        path: "{{ mountpoint }}"
        fstype: cifs
        opts: 'username={{ username }}, password={{ password }}'
        state: mounted
        
      
