---
- name: unarchive module demo  # Использование модуля распаковки архивов
  hosts: all 
  become: true  # Выполняем задачи с правами суперпользователя (sudo), так как для работы с некоторыми путями могут потребоваться повышенные привилегии
  vars:
    myurl: "https://github.com/lucab85/ansible-pilot/archive/refs/heads/master.zip"  # URL архива, который мы будем загружать и распаковывать
  tasks:  # Определение списка задач, которые будут выполняться на целевых хостах

    - name: Ensure destination directory exists  # Первая задача — проверка, существует ли директория для распаковки
      file:
        path: "/home/mity/Загрузки"  # Указываем путь к директории, куда будем распаковывать архив
        state: directory  # Проверяем, что это директория. Если её нет, она будет создана
      # Зачем это нужно: Перед распаковкой важно убедиться, что директория назначения существует. Иначе распаковка может завершиться ошибкой.

    - name: Download archive  # Вторая задача — скачивание архива
      get_url:
        url: "{{ myurl }}"  # Используем переменную с URL для загрузки архива
        dest: "/tmp/master.zip"  # Указываем путь, куда будет загружен архив на локальную машину
        validate_certs: true  # Проверяем SSL-сертификаты при загрузке, чтобы убедиться в безопасности соединения
      # Зачем это нужно: Скачиваем архив с удалённого ресурса и сохраняем его на локальной машине в директорию /tmp. Используем проверку сертификатов для безопасности.

    - name: Extract archive  # Третья задача — распаковка загруженного архива
      unarchive:
        src: "/tmp/master.zip"  # Указываем путь к загруженному архиву
        dest: "/home/mity/Загрузки"  # Путь назначения для распаковки файлов
        remote_src: true  # Указываем, что архив находится на удалённой машине
      # Зачем это нужно: После загрузки архив нужно распаковать в нужную директорию. Модуль `unarchive` распаковывает файл, поддерживая различные форматы архивов.

    - name: Set permissions on extracted files  # Четвёртая задача — настройка прав доступа на файлы
      file:
        path: "/home/mity/Загрузки"  # Путь к директории с распакованными файлами
        state: directory  # Подтверждаем, что работаем с директорией
        mode: '0755'  # Устанавливаем права доступа на директорию и все файлы внутри неё (0755 — стандартные права на чтение, запись для владельца и на чтение для остальных)
      # Зачем это нужно: После распаковки файлов можно задать нужные права доступа, чтобы файлы и директория были доступны согласно политике безопасности (чтение для всех, запись только для владельца).


