---
- name: Install Apache WebServer
  hosts: apachesrvs
  become: true
  
  tasks:
  - name: Instiall Apache on Ubuntu Server
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"


  - name: Install Apache on Centos Server
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"      
