---
- name: Installing and Running apache
  hosts: testsrv1
  become: yes  

  tasks:
    - name: install apache latest
      apt: name=apache2 update_cache=yes state=latest 
      tags: i-apache2


    - name: open port
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp  
      tags: o-port    
                

