---
# Плейбук для удаления одного или нескольких пользователей, включая их домашние директории и почтовые ящики

- name: User Deletion Playbook
  hosts: all
  become: true  # Выполняем задачи от имени суперпользователя (root)
  vars:
    users_to_delete:  # Список пользователей, которых нужно удалить
      - example1
      - example2
      - example3  # Добавьте сюда нужных пользователей

  tasks:
    - name: Проверка существования пользователя
      command: "id -u {{ item }}"  # Проверяем существование пользователя по его UID
      register: user_check  # Регистрируем результат команды
      ignore_errors: true  # Игнорируем ошибки, если пользователь не существует
      loop: "{{ users_to_delete }}"  # Проходим по списку пользователей

    - name: Удаление существующего пользователя и его домашней директории
      user:
        name: "{{ item.item }}"  # Указываем имя пользователя
        state: absent  # Указываем, что пользователь должен быть удалён
        remove: true  # Удаляем домашнюю директорию и почтовый ящик
      when: item.rc == 0  # Выполняем, если пользователь найден
      loop: "{{ user_check.results }}"  # Проходим по результатам проверки пользователей
      loop_control:
        label: "{{ item.item }}"  # Показываем в логах имя пользователя, а не индекс

    - name: Логирование удаления пользователя
      debug:
        msg: "Пользователь '{{ item.item }}' успешно удалён."
      when: item.rc == 0  # Логируем успешное удаление
      loop: "{{ user_check.results }}"  # Проходим по результатам проверки пользователей
      loop_control:
        label: "{{ item.item }}"  # Показываем в логах имя пользователя, а не индекс

    - name: Логирование отсутствия пользователя
      debug:
        msg: "Пользователь '{{ item.item }}' не существует."
      when: item.rc != 0  # Логируем, если пользователь не найден
      loop: "{{ user_check.results }}"  # Проходим по результатам проверки пользователей
      loop_control:
        label: "{{ item.item }}"  # Показываем в логах имя пользователя, а не индекс
